owner: frafra
repo: ohsome-api-upptime

sites:
  - name: api.ohsome.org - elements/area
    url: https://api.ohsome.org/v1/elements/area?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&format=json&time=2014-01-01

status-website:
  baseUrl: /ohsome-api-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor api.ohsome.org with Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page to monitor api.ohsome.org status using [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
